### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by r4fterman** [niwo/xantora#3]
Hi,
as the documentation is just the README.md currently it gives the hint of theme support.

But can you provide an example on how to pass in a custom theme into the PDF generation process?

Thanks, Roman

**Comment by niwo** [comment]
Hi Roman,

You're right - documentation on theme support is lacking.

Using the ‘--attributes‘ switch in the cli you should be able to specify values for ‘pdf-theme‘, ‘pdf-themesdir‘ and ‘pdf-fontsdir‘.

See https://github.com/niwo/xantora/blob/0f92fa988c6ea6c679a5f533cddf67969728c1cd/lib/xantora/document.rb#L87 where the default values are being set.

I hope this helps.

Cheers,
Nik
